# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import calendar_pb2 as calendar__pb2


class CalendarStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetEvents = channel.unary_stream(
                '/Calendar/GetEvents',
                request_serializer=calendar__pb2.User.SerializeToString,
                response_deserializer=calendar__pb2.Event.FromString,
                )
        self.CreateEvent = channel.unary_unary(
                '/Calendar/CreateEvent',
                request_serializer=calendar__pb2.NewEvent.SerializeToString,
                response_deserializer=calendar__pb2.Event.FromString,
                )


class CalendarServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CalendarServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.GetEvents,
                    request_deserializer=calendar__pb2.User.FromString,
                    response_serializer=calendar__pb2.Event.SerializeToString,
            ),
            'CreateEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateEvent,
                    request_deserializer=calendar__pb2.NewEvent.FromString,
                    response_serializer=calendar__pb2.Event.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Calendar', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Calendar(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/Calendar/GetEvents',
            calendar__pb2.User.SerializeToString,
            calendar__pb2.Event.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Calendar/CreateEvent',
            calendar__pb2.NewEvent.SerializeToString,
            calendar__pb2.Event.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
